<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>
<%@ page import = "model.entities.*" %>
<%@ page import = "authn.*" %>
<%@ page import = "java.util.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                "INSERT INTO " + schema + ".TOPIC VALUES (NEXT VALUE FOR TOPIC_GEN, 'Computer Science')",
               // "INSERT INTO " + schema + ".COMMENT VALUES (NEXT VALUE FOR COMMENT_GEN, 'Skeleton code', 1)",
               // "INSERT INTO " + schema + ".COMMENT VALUES (NEXT VALUE FOR COMMENT_GEN, 'for homework1', 1)",
                "INSERT INTO " + schema + ".CREDENTIALS VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')",
                // Poblar tabla Article
                "INSERT INTO " + schema + ".ARTICLE (id, title, authorName, datePublished, views, featuredImage, content) VALUES (NEXT VALUE FOR ARTICLE_GEN, 'Understanding Java Streams', 'Ana Rodriguez', DATE('2023-09-15'), 3300, 'image1.jpg', 'Java Streams simplify processing of collections and streams in functional programming style.')",
                "INSERT INTO " + schema + ".ARTICLE (id, title, authorName, datePublished, views, featuredImage, content) VALUES (NEXT VALUE FOR ARTICLE_GEN, 'Exploring REST APIs', 'Jana Gomez', DATE('2023-08-10'), 1200, 'image2.jpg', 'REST APIs are essential for building scalable services.')",
                "INSERT INTO " + schema + ".ARTICLE (id, title, authorName, datePublished, views, featuredImage, content) VALUES (NEXT VALUE FOR ARTICLE_GEN, 'Modern Database Design', 'Jaime Lopez', DATE('2023-07-20'), 2200,'image3.jpg', 'This article covers normalization and database schemas.')",
    
                // Poblar tabla Customer
                "INSERT INTO " + schema + ".CUSTOMER (id, username, firstName, lastName, email, isAuthor) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'maria14_tgn', 'Maria', 'Sevilla', 'maria14@example.com',  1)",
                "INSERT INTO " + schema + ".CUSTOMER (id, username, firstName, lastName, email, isAuthor) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'jana_lopz', 'Jana', 'Lopez', 'janal@example.com', 1)",
                "INSERT INTO " + schema + ".CUSTOMER (id, username, firstName, lastName, email, isAuthor) VALUES (NEXT VALUE FOR CUSTOMER_GEN, 'lector123', 'Susana', 'Fernandez', 'susif@example.com',0)"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
